### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by olivierlacan** [tylerhunt/coercion#2]
Would you mind giving a good use case for this gem? I'm curious in which situations it came in handy.

**Comment by tylerhunt** [comment]
It was written primarily to solve the issue of form data from blank fields coming into Rails controllers as empty strings, but wanting them to be written into the database as `nil` values. It prevents the case where you end up with both `nil` and blank strings in the database, which can be painful when querying to find records without values in certain columns (`WHERE name IS NOT NULL OR name = ''`).

**Comment by olivierlacan** [comment]
The timing of your answer is uncanny. Just had to deal with this with virtual store_accessor attributes in Rails 4.
